# docker-compose.yml
version: '3.8'
services:
  awscdk:
    build: .
    environment:
      - AWS_SDK_LOAD_CONFIG=1
    entrypoint: ""
    working_dir: /work
    volumes:
      - .:/work
      - ~/.aws:/root/.aws
